services:
  - type: web
    name: taja-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn taja_backend.wsgi
    envVars:
      - key: DEBUG
        value: False
      - key: DB_NAME
        value: neondb
      - key: DB_USER
        value: neondb_owner
      - key: DB_PASSWORD
        value: npg_Av3JE5qRKXtI
      - key: DB_HOST
        value: ep-dry-sunset-ahyt6lpy-pooler.c-3.us-east-1.aws.neon.tech
      - key: DB_PORT
        value: 5432
      - key: DB_SSLMODE
        value: require
      - key: DJANGO_ALLOWED_HOSTS
        value: your-app-name.onrender.com
